import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:poker_guy/models/app_user.dart';
import 'package:poker_guy/models/poker_table.dart';
import 'package:poker_guy/models/hole_cards.dart';
import 'package:poker_guy/models/table_player_names.dart';

class DatabaseService {

  final FirebaseFirestore _db = FirebaseFirestore.instance;
  final CollectionReference appUserCollection = FirebaseFirestore.instance.collection("app_users");
  final CollectionReference tableCollection = FirebaseFirestore.instance.collection("tables");

  final String uid;
  final String tableId;
  DatabaseService({this.uid = "", this.tableId = "" });

  Stream<PokerTable> get table {

    return tableCollection
        .doc(tableId)
        .snapshots()
        .map((snap) => PokerTable.fromMap(snap.data));
  }

  Stream<TablePlayerNames> get tablePlayers {

    return tableCollection
        .doc(tableId).collection("tablePlayers")
        .snapshots()
        .map((snap) => TablePlayerNames.fromSnapshots(snap));
  }

  Stream<HoleCards> get holeCards {

    if (this.uid == null) {
      return null;
    }
    return appUserCollection
        .doc(uid)
        .snapshots()
        .map((snap) => HoleCards.fromMap(snap.data));
  }

  Stream<TablePlayerNames> get tablePlayerNames {

    if (this.tableId== null) {
      return null;
    }
    return tableCollection
        .doc(tableId)
        .collection("tablePlayers")
        .snapshots()
        .map((snap) => TablePlayerNames.fromSnapshots(snap));
  }

  Stream<AppUser> get appUser {

    if (this.uid == null) {
      return null;
    }
    return appUserCollection
        .doc(uid)
        .snapshots()
        .map((snap) => AppUser.fromMap(snap.data));
  }

  void playerFolds(AppUser appUser) {
    String puid = appUser.uid;
    if (puid == null) {
      return null;
    }
    appUserCollection.doc(puid).update({"holeCard1": ""});
    appUserCollection.doc(puid).update({"holeCard2": ""});

    updateAppUser(appUser);
  }

  void shuffleOff() {

    tableCollection.doc(tableId).update({"tableState": 3,
                                          "shuffling": false});
  }


  Future<void> updateAppUser(AppUser appUser) async {

    if (uid == null) {
      return null;
    }

    return await appUserCollection.doc(uid).set(appUser.toMap())
        .then((value) => print("User Updated"))
        .catchError((error) => print("Failed to update user: $error"));
  }

  void loadWordsToFirestore() {
    // Just a throw away function to load words into firestore
    final CollectionReference phraseWordsCollection = FirebaseFirestore.instance.collection("words");
    Map<String, dynamic> nouns = {
      '1': 'ball',
      '2': 'bat',
      '3': 'bed',
      '4': 'book',
      '5': 'boy',
      '6': 'bun',
      '7': 'can',
      '8': 'cake',
      '9': 'cap',
      '10': 'car',
      '11': 'cat',
      '12': 'cow',
      '13': 'cub',
      '14': 'cup',
    };
    Map<String, dynamic> adjectives = {
      '1': 'quizzical',
      '2': 'highfalutin',
      '3': 'dynamic',
      '4': 'wakeful',
      '5': 'cheerful',
      '6': 'thoughtful',
      '7': 'cooperative',
      '8': 'questionable',
      '9': 'abundant',
      '10': 'uneven',
      '11': 'yummy',
      '12': 'juicy',
      '13': 'vacuous',
      '14': 'concerned',
      // '15': 'young',
      // '16': 'sparkling',
      // '17': 'abhorrent',
      // '18': 'sweltering',
      // '19': 'late',
      // '20': 'macho',
      // '21': 'scrawny',
      // '22': 'friendly',
      // '23': 'kaput',
      // '24': 'divergent',
      // '25': 'busy',
      // '26': 'charming',
      // '27': 'protective',
      // '28': 'premium',
      // '29': 'puzzled',
      // '30': 'waggish',
      // '31': 'rambunctious',
      // '32': 'puffy',
      // '33': 'hard',
      // '34': 'fat',
      // '35': 'sedate',
      // '36': 'yellow',
      // '37': 'resonant',
      // '38': 'dapper',
      // '39': 'courageous',
      // '40': 'vast',
      // '41': 'cool',
      // '42': 'elated',
      // '43': 'wary',
      // '44': 'bewildered',
      // '45': 'level',
      // '46': 'wooden',
      // '47': 'ceaseless',
      // '48': 'tearful',
      // '49': 'cloudy',
      // '50': 'gullible',
      // '51': 'flashy',
      // '52': 'trite',
      // '53': 'quick',
      // '54': 'nondescript',
      // '55': 'round',
      // '56': 'slow',
      // '57': 'spiritual',
      // '58': 'brave',
      // '59': 'tenuous',
      // '60': 'abstracted',
      // '61': 'colossal',
      // '62': 'sloppy',
      // '63': 'obsolete',
      // '64': 'elegant',
      // '65': 'fabulous',
      // '66': 'vivacious',
      // '67': 'exuberant',
      // '68': 'faithful',
      // '69': 'helpless',
      // '70': 'odd',
      // '71': 'sordid',
      // '72': 'blue',
      // '73': 'imported',
      // '74': 'ugly',
      // '75': 'ruthless',
      // '76': 'deeply',
      // '77': 'eminent',
      // '78': 'reminiscent',
      // '79': 'rotten',
      // '80': 'sour',
      // '81': 'volatile',
      // '82': 'succinct',
      // '83': 'judicious',
      // '84': 'abrupt',
      // '85': 'learned',
      // '86': 'stereotyped',
      // '87': 'evanescent',
      // '88': 'efficacious',
      // '89': 'festive',
      // '90': 'loose',
      // '91': 'torpid',
      // '92': 'condemned',
      // '93': 'selective',
      // '94': 'strong',
      // '95': 'momentous',
      // '96': 'ordinary',
      // '97': 'dry',
      // '98': 'great',
      // '99': 'ultra',
      // '100': 'ahead',
      // '101': 'broken',
      // '102': 'dusty',
      // '103': 'piquant',
      // '104': 'creepy',
      // '105': 'miniature',
      // '106': 'periodic',
      // '107': 'equable',
      // '108': 'unsightly',
      // '109': 'narrow',
      // '110': 'grieving',
      // '111': 'whimsical',
      // '112': 'fantastic',
      // '113': 'kindhearted',
      // '114': 'miscreant',
      // '115': 'cowardly',
      // '116': 'cloistered',
      // '117': 'marked',
      // '118': 'bloody',
      // '119': 'chunky',
      // '120': 'undesirable',
      // '121': 'oval',
      // '122': 'nauseating',
      // '123': 'aberrant',
      // '124': 'stingy',
      // '125': 'standing',
      // '126': 'distinct',
      // '127': 'illegal',
      // '128': 'angry',
      // '129': 'faint',
      // '130': 'rustic',
      // '131': 'few',
      // '132': 'calm',
      // '133': 'gorgeous',
      // '134': 'mysterious',
      // '135': 'tacky',
      // '136': 'unadvised',
      // '137': 'greasy',
      // '138': 'minor',
      // '139': 'loving',
      // '140': 'melodic',
      // '141': 'flat',
      // '142': 'wretched',
      // '143': 'clever',
      // '144': 'barbarous',
      // '145': 'pretty',
      // '146': 'endurable',
      // '147': 'handsomely',
      // '148': 'unequaled',
      // '149': 'acceptable',
      // '150': 'symptomatic',
      // '151': 'hurt',
      // '152': 'tested',
      // '153': 'long',
      // '154': 'warm',
      // '155': 'ignorant',
      // '156': 'ashamed',
      // '157': 'excellent',
      // '158': 'known',
      // '159': 'adamant',
      // '160': 'eatable',
      // '161': 'verdant',
      // '162': 'meek',
      // '163': 'unbiased',
      // '164': 'rampant',
      // '165': 'somber',
      // '166': 'cuddly',
      // '167': 'harmonious',
      // '168': 'salty',
      // '169': 'overwrought',
      // '170': 'stimulating',
      // '171': 'beautiful',
      // '172': 'crazy',
      // '173': 'grouchy',
      // '174': 'thirsty',
      // '175': 'joyous',
      // '176': 'confused',
      // '177': 'terrible',
      // '178': 'high',
      // '179': 'unarmed',
      // '180': 'gabby',
      // '181': 'wet',
      // '182': 'sharp',
      // '183': 'wonderful',
      // '184': 'magenta',
      // '185': 'tan',
      // '186': 'huge',
      // '187': 'productive',
      // '188': 'defective',
      // '189': 'chilly',
      // '190': 'needy',
      // '191': 'imminent',
      // '192': 'flaky',
      // '193': 'fortunate',
      // '194': 'neighborly',
      // '195': 'hot',
      // '196': 'husky',
      // '197': 'optimal',
      // '198': 'gaping',
      // '199': 'faulty',
      // '200': 'guttural',
      // '201': 'massive',
      // '202': 'watery',
      // '203': 'abrasive',
      // '204': 'ubiquitous',
      // '205': 'aspiring',
      // '206': 'impartial',
      // '207': 'annoyed',
      // '208': 'billowy',
      // '209': 'lucky',
      // '210': 'panoramic',
      // '211': 'heartbreaking',
      // '212': 'fragile',
      // '213': 'purring',
      // '214': 'wistful',
      // '215': 'burly',
      // '216': 'filthy',
      // '217': 'psychedelic',
      // '218': 'harsh',
      // '219': 'disagreeable',
      // '220': 'ambiguous',
      // '221': 'short',
      // '222': 'splendid',
      // '223': 'crowded',
      // '224': 'light',
      // '225': 'yielding',
      // '226': 'hypnotic',
      // '227': 'dispensable',
      // '228': 'deserted',
      // '229': 'nonchalant',
      // '230': 'green',
      // '231': 'puny',
      // '232': 'deafening',
      // '233': 'classy',
      // '234': 'tall',
      // '235': 'typical',
      // '236': 'exclusive',
      // '237': 'materialistic',
      // '238': 'mute',
      // '239': 'shaky',
      // '240': 'inconclusive',
      // '241': 'rebellious',
      // '242': 'doubtful',
      // '243': 'telling',
      // '244': 'unsuitable',
      // '245': 'woebegone',
      // '246': 'cold',
      // '247': 'sassy',
      // '248': 'arrogant',
      // '249': 'perfect',
      // '250': 'adhesive',
      // '251': 'industrious',
      // '252': 'crabby',
      // '253': 'curly',
      // '254': 'voiceless',
      // '255': 'nostalgic',
      // '256': 'better',
      // '257': 'slippery',
      // '258': 'willing',
      // '259': 'nifty',
      // '260': 'orange',
      // '261': 'victorious',
      // '262': 'ritzy',
      // '263': 'wacky',
      // '264': 'vigorous',
      // '265': 'spotless',
      // '266': 'good',
      // '267': 'powerful',
      // '268': 'bashful',
      // '269': 'soggy',
      // '270': 'grubby',
      // '271': 'moaning',
      // '272': 'placid',
      // '273': 'permissible',
      // '274': 'half',
      // '275': 'towering',
      // '276': 'bawdy',
      // '277': 'measly',
      // '278': 'abaft',
      // '279': 'delightful',
      // '280': 'goofy',
      // '281': 'capricious',
      // '282': 'nonstop',
      // '283': 'addicted',
      // '284': 'acoustic',
      // '285': 'furtive',
      // '286': 'erratic',
      // '287': 'heavy',
      // '288': 'square',
      // '289': 'delicious',
      // '290': 'needless',
      // '291': 'resolute',
      // '292': 'innocent',
      // '293': 'abnormal',
      // '294': 'hurried',
      // '295': 'awful',
      // '296': 'impossible',
      // '297': 'aloof',
      // '298': 'giddy',
      // '299': 'large',
      // '300': 'pointless',
      // '301': 'petite',
      // '302': 'jolly',
      // '303': 'boundless',
      // '304': 'abounding',
      // '305': 'hilarious',
      // '306': 'heavenly',
      // '307': 'honorable',
      // '308': 'squeamish',
      // '309': 'red',
      // '310': 'phobic',
      // '311': 'trashy',
      // '312': 'pathetic',
      // '313': 'parched',
      // '314': 'godly',
      // '315': 'greedy',
      // '316': 'pleasant',
      // '317': 'small',
      // '318': 'aboriginal',
      // '319': 'dashing',
      // '320': 'icky',
      // '321': 'bumpy',
      // '322': 'laughable',
      // '323': 'hapless',
      // '324': 'silent',
      // '325': 'scary',
      // '326': 'shaggy',
      // '327': 'organic',
      // '328': 'unbecoming',
      // '329': 'inexpensive',
      // '330': 'wrong',
      // '331': 'repulsive',
      // '332': 'flawless',
      // '333': 'labored',
      // '334': 'disturbed',
      // '335': 'aboard',
      // '336': 'gusty',
      // '337': 'loud',
      // '338': 'jumbled',
      // '339': 'exotic',
      // '340': 'vulgar',
      // '341': 'threatening',
      // '342': 'belligerent',
      // '343': 'synonymous',
      // '344': 'encouraging',
      // '345': 'fancy',
      // '346': 'embarrassed',
      // '347': 'clumsy',
      // '348': 'fast',
      // '349': 'ethereal',
      // '350': 'chubby',
      // '351': 'high-pitched',
      // '352': 'plastic',
      // '353': 'open',
      // '354': 'straight',
      // '355': 'little',
      // '356': 'ancient',
      // '357': 'fair',
      // '358': 'psychotic',
      // '359': 'murky',
      // '360': 'earthy',
      // '361': 'callous',
      // '362': 'heady',
      // '363': 'lamentable',
      // '364': 'hallowed',
      // '365': 'obtainable',
      // '366': 'toothsome',
      // '367': 'oafish',
      // '368': 'gainful',
      // '369': 'flippant',
      // '370': 'tangy',
      // '371': 'tightfisted',
      // '372': 'damaging',
      // '373': 'utopian',
      // '374': 'gaudy',
      // '375': 'brainy',
      // '376': 'imperfect',
      // '377': 'shiny',
      // '378': 'fanatical',
      // '379': 'snotty',
      // '380': 'relieved',
      // '381': 'shallow',
      // '382': 'foamy',
      // '383': 'parsimonious',
      // '384': 'gruesome',
      // '385': 'elite',
      // '386': 'wide',
      // '387': 'kind',
      // '388': 'bored',
      // '389': 'tangible',
      // '390': 'depressed',
      // '391': 'boring',
      // '392': 'screeching',
      // '393': 'outrageous',
      // '394': 'determined',
      // '395': 'picayune',
      // '396': 'glossy',
      // '397': 'historical',
      // '398': 'staking',
      // '399': 'curious',
      // '400': 'gigantic',
      // '401': 'wandering',
      // '402': 'profuse',
      // '403': 'vengeful',
      // '404': 'glib',
      // '405': 'unaccountable',
      // '406': 'frightened',
      // '407': 'outstanding',
      // '408': 'chivalrous',
      // '409': 'workable',
      // '410': 'modern',
      // '411': 'swanky',
      // '412': 'comfortable',
      // '413': 'gentle',
      // '414': 'substantial',
      // '415': 'brawny',
      // '416': 'curved',
      // '417': 'nebulous',
      // '418': 'boorish',
      // '419': 'afraid',
      // '420': 'fierce',
      // '421': 'efficient',
      // '422': 'lackadaisical',
      // '423': 'recondite',
      // '424': 'internal',
      // '425': 'absorbed',
      // '426': 'squealing',
      // '427': 'frail',
      // '428': 'thundering',
      // '429': 'wanting',
      // '430': 'cooing',
      // '431': 'axiomatic',
      // '432': 'debonair',
      // '433': 'boiling',
      // '434': 'tired',
      // '435': 'numberless',
      // '436': 'flowery',
      // '437': 'mushy',
      // '438': 'enthusiastic',
      // '439': 'proud',
      // '440': 'upset',
      // '441': 'hungry',
      // '442': 'astonishing',
      // '443': 'deadpan',
      // '444': 'prickly',
      // '445': 'mammoth',
      // '446': 'absurd',
      // '447': 'clean',
      // '448': 'jittery',
      // '449': 'wry',
      // '450': 'entertaining',
      // '451': 'literate',
      // '452': 'lying',
      // '453': 'uninterested',
      // '454': 'aquatic',
      // '455': 'super',
      // '456': 'languid',
      // '457': 'cute',
      // '458': 'absorbing',
      // '459': 'scattered',
      // '460': 'brief',
      // '461': 'halting',
      // '462': 'bright',
      // '463': 'fuzzy',
      // '464': 'lethal',
      // '465': 'scarce',
      // '466': 'aggressive',
      // '467': 'obsequious',
      // '468': 'fine',
      // '469': 'giant',
      // '470': 'holistic',
      // '471': 'pastoral',
      // '472': 'stormy',
      // '473': 'quaint',
      // '474': 'nervous',
      // '475': 'wasteful',
      // '476': 'grotesque',
      // '477': 'loutish',
      // '478': 'abiding',
      // '479': 'unable',
      // '480': 'black',
      // '481': 'dysfunctional',
      // '482': 'knowledgeable',
      // '483': 'truculent',
      // '484': 'various',
      // '485': 'luxuriant',
      // '486': 'shrill',
      // '487': 'spiffy',
      // '488': 'guarded',
      // '489': 'colorful',
      // '490': 'misty',
      // '491': 'spurious',
      // '492': 'freezing',
      // '493': 'glamorous',
      // '494': 'famous',
      // '495': 'new',
      // '496': 'instinctive',
      // '497': 'nasty',
      // '498': 'exultant',
      // '499': 'seemly',
      // '500': 'tawdry',
      // '501': 'maniacal',
      // '502': 'wrathful',
      // '503': 'shy',
      // '504': 'nutritious',
      // '505': 'idiotic',
      // '506': 'worried',
      // '507': 'bad',
      // '508': 'stupid',
      // '509': 'ruddy',
      // '510': 'wholesale',
      // '511': 'naughty',
      // '512': 'thoughtless',
      // '513': 'futuristic',
      // '514': 'available',
      // '515': 'slimy',
      // '516': 'cynical',
      // '517': 'fluffy',
      // '518': 'plausible',
      // '519': 'nasty ',
      // '520': 'tender',
      // '521': 'changeable',
      // '522': 'smiling',
      // '523': 'oceanic',
      // '524': 'satisfying',
      // '525': 'steadfast',
      // '526': 'ugliest',
      // '527': 'crooked',
      // '528': 'subsequent',
      // '529': 'fascinated',
      // '530': 'woozy',
      // '531': 'teeny',
      // '532': 'quickest',
      // '533': 'moldy',
      // '534': 'uppity',
      // '535': 'sable',
      // '536': 'horrible',
      // '537': 'silly',
      // '538': 'ad hoc',
      // '539': 'numerous',
      // '540': 'berserk',
      // '541': 'wiry',
      // '542': 'knowing',
      // '543': 'lazy',
      // '544': 'childlike',
      // '545': 'zippy',
      // '546': 'fearless',
      // '547': 'pumped',
      // '548': 'weak',
      // '549': 'tacit',
      // '550': 'weary',
      // '551': 'rapid',
      // '552': 'precious',
      // '553': 'smoggy',
      // '554': 'swift',
      // '555': 'lyrical',
      // '556': 'steep',
      // '557': 'quack',
      // '558': 'direful',
      // '559': 'talented',
      // '560': 'hesitant',
      // '561': 'fallacious',
      // '562': 'ill',
      // '563': 'quarrelsome',
      // '564': 'quiet',
      // '565': 'flipped-out',
      // '566': 'didactic',
      // '567': 'fluttering',
      // '568': 'glorious',
      // '569': 'tough',
      // '570': 'sulky',
      // '571': 'elfin',
      // '572': 'abortive',
      // '573': 'sweet',
      // '574': 'habitual',
      // '575': 'supreme',
      // '576': 'hollow',
      // '577': 'possessive',
      // '578': 'inquisitive',
      // '579': 'adjoining',
      // '580': 'incandescent',
      // '581': 'lowly',
      // '582': 'majestic',
      // '583': 'bizarre',
      // '584': 'acrid',
      // '585': 'expensive',
      // '586': 'aback',
      // '587': 'unusual',
      // '588': 'foolish',
      // '589': 'jobless',
      // '590': 'capable',
      // '591': 'damp',
      // '592': 'political',
      // '593': 'dazzling',
      // '594': 'erect',
      // '595': 'Early',
      // '596': 'immense',
      // '597': 'hellish',
      // '598': 'omniscient',
      // '599': 'reflective',
      // '600': 'lovely',
      // '601': 'incompetent',
      // '602': 'empty',
      // '603': 'breakable',
      // '604': 'educated',
      // '605': 'easy',
      // '606': 'devilish',
      // '607': 'assorted',
      // '608': 'decorous',
      // '609': 'jaded',
      // '610': 'homely',
      // '611': 'dangerous',
      // '612': 'adaptable',
      // '613': 'coherent',
      // '614': 'dramatic',
      // '615': 'tense',
      // '616': 'abject',
      // '617': 'fretful',
      // '618': 'troubled',
      // '619': 'diligent',
      // '620': 'solid',
      // '621': 'plain',
      // '622': 'raspy',
      // '623': 'irate',
      // '624': 'offbeat',
      // '625': 'healthy',
      // '626': 'melted',
      // '627': 'cagey',
      // '628': 'many',
      // '629': 'wild',
      // '630': 'venomous',
      // '631': 'animated',
      // '632': 'alike',
      // '633': 'youthful',
      // '634': 'ripe',
      // '635': 'alcoholic',
      // '636': 'sincere',
      // '637': 'teeny-tiny',
      // '638': 'lush',
      // '639': 'defeated',
      // '640': 'zonked',
      // '641': 'foregoing',
      // '642': 'dizzy',
      // '643': 'frantic',
      // '644': 'obnoxious',
      // '645': 'funny',
      // '646': 'damaged',
      // '647': 'grandiose',
      // '648': 'spectacular',
      // '649': 'maddening',
      // '650': 'defiant',
      // '651': 'makeshift',
      // '652': 'strange',
      // '653': 'painstaking',
      // '654': 'merciful',
      // '655': 'madly',
      // '656': 'clammy',
      // '657': 'itchy',
      // '658': 'difficult',
      // '659': 'clear',
      // '660': 'used',
      // '661': 'temporary',
      // '662': 'abandoned',
      // '663': 'null',
      // '664': 'rainy',
      // '665': 'evil',
      // '666': 'alert',
      // '667': 'domineering',
      // '668': 'amuck',
      // '669': 'rabid',
      // '670': 'jealous',
      // '671': 'robust',
      // '672': 'obeisant',
      // '673': 'overt',
      // '674': 'enchanting',
      // '675': 'longing',
      // '676': 'cautious',
      // '677': 'motionless',
      // '678': 'bitter',
      // '679': 'anxious',
      // '680': 'craven',
      // '681': 'breezy',
      // '682': 'ragged',
      // '683': 'skillful',
      // '684': 'quixotic',
      // '685': 'knotty',
      // '686': 'grumpy',
      // '687': 'dark',
      // '688': 'draconian',
      // '689': 'alluring',
      // '690': 'magical',
      // '691': 'versed',
      // '692': 'humdrum',
      // '693': 'accurate',
      // '694': 'ludicrous',
      // '695': 'sleepy',
      // '696': 'envious',
      // '697': 'lavish',
      // '698': 'roasted',
      // '699': 'thinkable',
      // '700': 'overconfident',
      // '701': 'roomy',
      // '702': 'painful',
      // '703': 'wee',
      // '704': 'observant',
      // '705': 'old-fashioned',
      // '706': 'drunk',
      // '707': 'royal',
      // '708': 'likeable',
      // '709': 'adventurous',
      // '710': 'eager',
      // '711': 'obedient',
      // '712': 'attractive',
      // '713': 'x-rated',
      // '714': 'spooky',
      // '715': 'poised',
      // '716': 'righteous',
      // '717': 'excited',
      // '718': 'real',
      // '719': 'abashed',
      // '720': 'womanly',
      // '721': 'ambitious',
      // '722': 'lacking',
      // '723': 'testy',
      // '724': 'big',
      // '725': 'gamy',
      // '726': 'early',
      // '727': 'auspicious',
      // '728': 'blue-eyed ',
      // '729': 'discreet',
      // '730': 'nappy',
      // '731': 'vague',
      // '732': 'helpful',
      // '733': 'nosy',
      // '734': 'perpetual',
      // '735': 'disillusioned',
      // '736': 'overrated',
      // '737': 'gleaming',
      // '738': 'tart',
      // '739': 'soft',
      // '740': 'agreeable',
      // '741': 'therapeutic',
      // '742': 'accessible',
      // '743': 'poor',
      // '744': 'gifted',
      // '745': 'old',
      // '746': 'humorous',
      // '747': 'flagrant',
      // '748': 'magnificent',
      // '749': 'alive',
      // '750': 'understood',
      // '751': 'economic',
      // '752': 'mighty',
      // '753': 'ablaze',
      // '754': 'racial',
      // '755': 'tasteful',
      // '756': 'purple',
      // '757': 'broad',
      // '758': 'lean',
      // '759': 'legal',
      // '760': 'witty',
      // '761': 'nutty',
      // '762': 'icy',
      // '763': 'feigned',
      // '764': 'redundant',
      // '765': 'adorable',
      // '766': 'apathetic',
      // '767': 'jumpy',
      // '768': 'scientific',
      // '769': 'combative',
      // '770': 'worthless',
      // '771': 'tasteless',
      // '772': 'voracious',
      // '773': 'jazzy',
      // '774': 'uptight',
      // '775': 'utter',
      // '776': 'hospitable',
      // '777': 'imaginary',
      // '778': 'finicky',
      // '779': 'shocking',
      // '780': 'dead',
      // '781': 'noisy',
      // '782': 'shivering',
      // '783': 'subdued',
      // '784': 'rare',
      // '785': 'zealous',
      // '786': 'demonic',
      // '787': 'ratty',
      // '788': 'snobbish',
      // '789': 'deranged',
      // '790': 'muddy',
      // '791': 'whispering',
      // '792': 'credible',
      // '793': 'hulking',
      // '794': 'fertile',
      // '795': 'tight',
      // '796': 'abusive',
      // '797': 'functional',
      // '798': 'obscene',
      // '799': 'thankful',
      // '800': 'daffy',
      // '801': 'smelly',
      // '802': 'lively',
      // '803': 'homeless',
      // '804': 'secretive',
      // '805': 'amused',
      // '806': 'lewd',
      // '807': 'mere',
      // '808': 'agonizing',
      // '809': 'sad',
      // '810': 'innate',
      // '811': 'sneaky',
      // '812': 'noxious',
      // '813': 'illustrious',
      // '814': 'alleged',
      // '815': 'cultured',
      // '816': 'tame',
      // '817': 'macabre',
      // '818': 'lonely',
      // '819': 'mindless',
      // '820': 'low',
      // '821': 'scintillating',
      // '822': 'statuesque',
      // '823': 'decisive',
      // '824': 'rhetorical',
      // '825': 'hysterical',
      // '826': 'happy',
      // '827': 'earsplitting',
      // '828': 'mundane',
      // '829': 'spicy',
      // '830': 'overjoyed',
      // '831': 'taboo',
      // '832': 'peaceful',
      // '833': 'forgetful',
      // '834': 'elderly',
      // '835': 'upbeat',
      // '836': 'squalid',
      // '837': 'warlike',
      // '838': 'dull',
      // '839': 'plucky',
      // '840': 'handsome',
      // '841': 'groovy',
      // '842': 'absent',
      // '843': 'wise',
      // '844': 'romantic',
      // '845': 'invincible',
      // '846': 'receptive',
      // '847': 'smooth',
      // '848': 'different',
      // '849': 'tiny',
      // '850': 'cruel',
      // '851': 'dirty',
      // '852': 'mature',
      // '853': 'faded',
      // '854': 'tiresome',
      // '855': 'wicked',
      // '856': 'average',
      // '857': 'panicky',
      // '858': 'detailed',
      // '859': 'juvenile',
      // '860': 'scandalous',
      // '861': 'steady',
      // '862': 'wealthy',
      // '863': 'deep',
      // '864': 'sticky',
      // '865': 'jagged',
      // '866': 'wide-eyed',
      // '867': 'tasty',
      // '868': 'disgusted',
      // '869': 'garrulous',
      // '870': 'graceful',
      // '871': 'tranquil',
      // '872': 'annoying',
      // '873': 'hissing',
      // '874': 'noiseless',
      // '875': 'selfish',
      // '876': 'onerous',
      // '877': 'lopsided',
      // '878': 'ossified',
      // '879': 'penitent',
      // '880': 'malicious',
      // '881': 'aromatic',
      // '882': 'successful',
      // '883': 'zany',
      // '884': 'evasive',
      // '885': 'wet ',
      // '886': 'naive',
      // '887': 'nice',
      // '888': 'uttermost',
      // '889': 'brash',
      // '890': 'muddled',
      // '891': 'energetic',
      // '892': 'accidental',
      // '893': 'silky',
      // '894': 'guiltless',
      // '895': 'important',
      // '896': 'drab',
      // '897': 'aware',
      // '898': 'skinny',
      // '899': 'careful',
      // '900': 'rightful',
      // '901': 'tricky',
      // '902': 'sore',
      // '903': 'rich',
      // '904': 'blushing',
      // '905': 'stale',
      // '906': 'daily',
      // '907': 'watchful',
      // '908': 'uncovered',
      // '909': 'rough',
      // '910': 'fresh',
      // '911': 'hushed',
      // '912': 'rural',

    };

    phraseWordsCollection.doc("nouns").set(nouns);
  }

}
